longitud=float(input("Ingrese la longitud del rectpangulo: "))
ancho=float(input("Ingrese el ancho del ractángulo: "))
perimetro=float(2*longitud + 2*ancho)
area=float(longitud*ancho)
print("perímetro: ",perimetro)
print("área: ",area)

radio=float(input("Ingrese el radio de la circunferencia: "))
pi=float(3.14)
area_cir=float(2*pi*radio)
perimetro_cir=float(pi*radio^2)
print("Area de la circunferencia: ",area_cir)
print("Perímetro de la circunferencia: ",perimetro_cir)